name: Update README Activity
run-name: ${{github.actor}} is updating README activity
on:
  schedule:
    - cron: "* */1 * * *" # scheduled to run every hour
jobs:
  update-recent-activity: 
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Update README's most recent activity section
        run: |
          python -m pip install argparse
          python -m pip install requests
          python -m pip install datetime
          python github-python-test.py ${{secrets.GITHUB_TOKEN}}
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git config --global user.name "${{github.actor}}"
          git config --global user.email "${{github.actor}}@users.noreply.github.com"
          git add README.md
          git commit -m "Update activity in README"
          git push origin main
