name: Update README

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub - Activity - Readme
      # You may pin to the exact commit or the version.
      # uses: jamesgeorge007/github-activity-readme@338f4f82e1476c1519ab946bacba0ff3d8a23b92
      uses: jamesgeorge007/github-activity-readme@v0.3.6
      with:
        # Your GitHub username
        GH_USERNAME: ${{ github.repository_owner }} # optional, default is ${{ github.repository_owner }}
        # Commit message used while committing to the repo
        COMMIT_MSG: ":zap:" # optional, default is :zap: Update README with the recent activity
        # The maximum number of lines populated in your readme file
        MAX_LINES: 5 # optional, default is 5

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          
